/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import userInterface.ManageAirliners.ManageAirlinersJPanel;
import Business.AirlinerCatalog;
import Business.AirplaneCatalog;
import Business.CustomerCatalog;
import java.awt.CardLayout;
import userInterface.TravelAgency.ListAllFlights;
import userInterface.ManageCustomers.ManageCustomers;
import userInterface.TravelAgency.ManageFlights;
import userInterface.TravelAgency.SearchFlights;

/**
 *
 * @author Siddhi
 */
public class TravelAgencyMainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form TravelAgencyMainJFrame
     */
     private AirlinerCatalog aCatalog;
    private AirplaneCatalog airplaneC;
    private CustomerCatalog cCatalog;
    
    
    public TravelAgencyMainJFrame() {
        initComponents();
        this.aCatalog=new AirlinerCatalog();
        this.airplaneC=new AirplaneCatalog();
        this.cCatalog=new CustomerCatalog();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        ControlPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnManageAirlines = new javax.swing.JButton();
        btnSearchFlights = new javax.swing.JButton();
        btnListFlights = new javax.swing.JButton();
        btnManageFlights = new javax.swing.JButton();
        btnManageCust = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userControlDisplayPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ControlPanel.setBackground(new java.awt.Color(0, 102, 102));
        ControlPanel.setPreferredSize(new java.awt.Dimension(200, 465));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAGE TRAVEL AGENCY");

        btnManageAirlines.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnManageAirlines.setText("Manage Airliner");
        btnManageAirlines.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageAirlines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAirlinesActionPerformed(evt);
            }
        });

        btnSearchFlights.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearchFlights.setText("Search Flights");
        btnSearchFlights.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearchFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFlightsActionPerformed(evt);
            }
        });

        btnListFlights.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnListFlights.setText("List all Flights");
        btnListFlights.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnListFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListFlightsActionPerformed(evt);
            }
        });

        btnManageFlights.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnManageFlights.setText("Manage Flights");
        btnManageFlights.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFlightsActionPerformed(evt);
            }
        });

        btnManageCust.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnManageCust.setText("Manage Customers");
        btnManageCust.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MANAGE CUSTOMERS");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REGISTER AIRLINERS");

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageFlights, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearchFlights, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListFlights, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageAirlines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageCust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlPanelLayout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ControlPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnManageFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageCust, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageAirlines, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(ControlPanel);

        userControlDisplayPanel.setBackground(new java.awt.Color(0, 102, 102));
        userControlDisplayPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userControlDisplayPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageAirlinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAirlinesActionPerformed
        // TODO add your handling code here:
        ManageAirlinersJPanel panel = new ManageAirlinersJPanel(userControlDisplayPanel, aCatalog);
        userControlDisplayPanel.add("ManageFlights",panel);
        CardLayout layout=(CardLayout)userControlDisplayPanel.getLayout();
        layout.next(userControlDisplayPanel);
        
    }//GEN-LAST:event_btnManageAirlinesActionPerformed

    private void btnSearchFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFlightsActionPerformed
        // TODO add your handling code here:
        SearchFlights panel = new SearchFlights(userControlDisplayPanel,airplaneC);
        userControlDisplayPanel.add("SearchFlights",panel);
        CardLayout layout =(CardLayout)userControlDisplayPanel.getLayout();
        layout.next(userControlDisplayPanel);
        
        
        
    }//GEN-LAST:event_btnSearchFlightsActionPerformed

    private void btnManageFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFlightsActionPerformed
        // TODO add your handling code here:
        ManageFlights panel = new ManageFlights(userControlDisplayPanel, airplaneC);
        userControlDisplayPanel.add("Manage Flights",panel);
        CardLayout layout =(CardLayout)userControlDisplayPanel.getLayout();
        layout.next(userControlDisplayPanel);
        
    }//GEN-LAST:event_btnManageFlightsActionPerformed

    private void btnListFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListFlightsActionPerformed
        // TODO add your handling code here:
        ListAllFlights panel = new ListAllFlights(userControlDisplayPanel, airplaneC);
        userControlDisplayPanel.add("ListAllFlights",panel);
        CardLayout layout =(CardLayout)userControlDisplayPanel.getLayout();
        layout.next(userControlDisplayPanel);
    }//GEN-LAST:event_btnListFlightsActionPerformed

    private void btnManageCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustActionPerformed
        // TODO add your handling code here:
        ManageCustomers panel = new ManageCustomers(userControlDisplayPanel, airplaneC);
        userControlDisplayPanel.add("ManageCustomers",panel);
     CardLayout layout=(CardLayout)userControlDisplayPanel.getLayout();
     layout.next(userControlDisplayPanel);
    }//GEN-LAST:event_btnManageCustActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelAgencyMainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JButton btnListFlights;
    private javax.swing.JButton btnManageAirlines;
    private javax.swing.JButton btnManageCust;
    private javax.swing.JButton btnManageFlights;
    private javax.swing.JButton btnSearchFlights;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel userControlDisplayPanel;
    // End of variables declaration//GEN-END:variables
}
