/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ManageAirliners;

import userInterface.ManageAirliners.ManageAirlinersJPanel;
import Business.Airliner;
import Business.AirlinerCatalog;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Siddhi
 */
public class CreateNewAirlinerJPanel extends javax.swing.JPanel {

    
    private JPanel userControlDisplayPanel;
    private AirlinerCatalog aCatalog;
    /**
     * Creates new form CreateAirline
     */
    public CreateNewAirlinerJPanel(JPanel userControlDisplayPanel,AirlinerCatalog aCatalog ) {
        initComponents();
        this.aCatalog =aCatalog;
        this.userControlDisplayPanel = userControlDisplayPanel;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtAirlineID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAirlineName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAirlineCompany = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAirlineFleetSize = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAirlineHeadQuarters = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CREATE AIRLINER DETAILS");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Airline ID :");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("< Back");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtAirlineID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAirlineID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirlineIDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Airline Name :");

        txtAirlineName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAirlineName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirlineNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Airline Company :");

        txtAirlineCompany.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAirlineCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirlineCompanyActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Fleet Size : ");

        txtAirlineFleetSize.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAirlineFleetSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirlineFleetSizeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Head Quarters :");

        txtAirlineHeadQuarters.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAirlineHeadQuarters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirlineHeadQuartersActionPerformed(evt);
            }
        });

        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(8, 8, 8)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAirlineName, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAirlineID, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAirlineCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAirlineFleetSize, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAirlineHeadQuarters, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1)))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAirlineID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAirlineName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAirlineCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAirlineFleetSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAirlineHeadQuarters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAirlineIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirlineIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirlineIDActionPerformed

    private void txtAirlineNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirlineNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirlineNameActionPerformed

    private void txtAirlineCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirlineCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirlineCompanyActionPerformed

    private void txtAirlineFleetSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirlineFleetSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirlineFleetSizeActionPerformed

    private void txtAirlineHeadQuartersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirlineHeadQuartersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirlineHeadQuartersActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        //Field level Validations
        String airlineID = txtAirlineID.getText();
        
        //Special Character Validation
        
        //AIRLINE ID VALIDATION
         if(!airlineIDPatternCorrect()){
         JOptionPane.showMessageDialog(null, "Airline ID should not contain any special characters!!");
         txtAirlineID.setBorder(BorderFactory.createLineBorder(Color.RED));
         jLabel1.setForeground(Color.RED);
         return;
     }  
        
       if(airlineID==null || airlineID.equals("")){
               JOptionPane.showMessageDialog(null, "Airliner ID can't be empty" );
               return;
           } 
       
        //AIRLINE NAME VALIDATION
        String airlineName = txtAirlineName.getText();
        if(airlineName==null || airlineName.equals("")){
               JOptionPane.showMessageDialog(null, "Airline Name can't be empty" );
               return; 
               
           }
        
        //Special Character Validation
         if(!airlineNamePatternCorrect()){
         JOptionPane.showMessageDialog(null, "Airline Name should not contain any special characters!!");
         txtAirlineName.setBorder(BorderFactory.createLineBorder(Color.RED));
         jLabel1.setForeground(Color.RED);
         return;
     }  
        
         
         //AIRLINE COMPANY FIELD VALIDATION
        String airlineCompany = txtAirlineCompany.getText();
        if(airlineCompany==null || airlineCompany.equals("")){
               JOptionPane.showMessageDialog(null, "Airliner Company can't be empty" );
               return; 
           }
        if(!airlineCompanyPatternCorrect()){
         JOptionPane.showMessageDialog(null, "Airline Company field should not contain any special characters!!");
         txtAirlineCompany.setBorder(BorderFactory.createLineBorder(Color.RED));
         jLabel1.setForeground(Color.RED);
         return;
     }  
        
        //FLEET SIZE FIELD VALIDATION
        
        int fleetSize = 0;
        
        try{
            
         fleetSize = Integer.parseInt(txtAirlineFleetSize.getText());
         
         
        
        }catch(NumberFormatException e)       
        {
        
        JOptionPane.showMessageDialog(null,"Please enter valid fleet size!!");
        return;
        }
        
        //HEADQUARTERS FIELD VALIDATION
         if(!headquartersPatternCorrect()){
         JOptionPane.showMessageDialog(null, "Headquarters field should not contain any special characters!!");
         txtAirlineHeadQuarters.setBorder(BorderFactory.createLineBorder(Color.RED));
         jLabel1.setForeground(Color.RED);
         return;
     }  
        
        String headquarters = txtAirlineHeadQuarters.getText();
        if(headquarters==null || headquarters.equals("")){
               JOptionPane.showMessageDialog(null, "Headquarters can't be empty !!" );
               return; 
           }
        
        Airliner airline = aCatalog.addAirliner();
        airline.setAirlineID(airlineID);
        airline.setAirlinerName(airlineName);
        airline.setAirlineCompany(airlineCompany);
        airline.setFleetSize(fleetSize);
        airline.setHeadquarters(headquarters);
        
        JOptionPane.showMessageDialog(null,"Airline Successfully Created!!");
        txtAirlineID.setText("");
        txtAirlineName.setText("");
        txtAirlineCompany.setText("");
        txtAirlineFleetSize.setText("");
        txtAirlineHeadQuarters.setText("");
        
        
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ManageAirlinersJPanel panel=new ManageAirlinersJPanel(userControlDisplayPanel, aCatalog);
        userControlDisplayPanel.add("CreateAirline",panel);
        CardLayout layout=(CardLayout)userControlDisplayPanel.getLayout();
        layout.next(userControlDisplayPanel);

        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAirlineCompany;
    private javax.swing.JTextField txtAirlineFleetSize;
    private javax.swing.JTextField txtAirlineHeadQuarters;
    private javax.swing.JTextField txtAirlineID;
    private javax.swing.JTextField txtAirlineName;
    // End of variables declaration//GEN-END:variables

    private boolean airlineIDPatternCorrect() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
       Pattern p = Pattern.compile("^[a-zA-Z0-9]+$");
       Matcher m = p.matcher(txtAirlineID.getText());
       boolean b = m.matches();
       return b;
    
    
    }

    private boolean airlineNamePatternCorrect() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    Pattern p = Pattern.compile("^[a-zA-Z0-9]+$");
       Matcher m = p.matcher(txtAirlineName.getText());
       boolean b = m.matches();
       return b;
    
    }

    private boolean airlineCompanyPatternCorrect() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
  
     Pattern p = Pattern.compile("^[a-zA-Z0-9]+$");
       Matcher m = p.matcher(txtAirlineCompany.getText());
       boolean b = m.matches();
       return b;
    
    
    }

    private boolean headquartersPatternCorrect() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
       Pattern p = Pattern.compile("^[a-zA-Z0-9]+$");
       Matcher m = p.matcher(txtAirlineHeadQuarters.getText());
       boolean b = m.matches();
       return b;
    
    
    
    }
}
