/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ManageAirliners;

import Business.Airliner;
import Business.AirlinerCatalog;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Siddhi
 */
public class ManageAirlinersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirlinersJPanel
     */
    
    private JPanel userControlDisplayPanel;
    private AirlinerCatalog aCatalog;
            
    public ManageAirlinersJPanel(JPanel userControlDisplayPanel, AirlinerCatalog aCatalog) {
        initComponents();
        this.aCatalog = aCatalog;
        this.userControlDisplayPanel = userControlDisplayPanel;
        populateTable();
        populateDets();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageAirliner = new javax.swing.JTable();
        btnCreateAirline = new javax.swing.JButton();
        btnViewAirline = new javax.swing.JButton();
        btnUpdateAirline = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MANAGE AIRLINER DETAILS");

        tblManageAirliner.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tblManageAirliner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner ID", "Airliner Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManageAirliner);
        if (tblManageAirliner.getColumnModel().getColumnCount() > 0) {
            tblManageAirliner.getColumnModel().getColumn(0).setResizable(false);
            tblManageAirliner.getColumnModel().getColumn(1).setResizable(false);
        }

        btnCreateAirline.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCreateAirline.setText("Create Airline");
        btnCreateAirline.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCreateAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAirlineActionPerformed(evt);
            }
        });

        btnViewAirline.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnViewAirline.setText("View Airline");
        btnViewAirline.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnViewAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAirlineActionPerformed(evt);
            }
        });

        btnUpdateAirline.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpdateAirline.setText("Update Airline");
        btnUpdateAirline.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUpdateAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAirlineActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCancel.setText("Cancel Airline");
        btnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnViewAirline, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(btnCreateAirline, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(btnUpdateAirline, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnCreateAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateTable()
    {
        DefaultTableModel dtm = (DefaultTableModel)tblManageAirliner.getModel();
        dtm.setRowCount(0);
        
        
        for(Airliner ai:aCatalog.getAirliner())
        {
            Object[] row = new Object[2];
            row[0]=ai;
            row[1]=ai.getAirlinerName();
            
            dtm.addRow(row);
        
        
        }
    
    }
    
    
    
    private void btnCreateAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAirlineActionPerformed
        // TODO add your handling code here:
        
        CreateNewAirlinerJPanel panel = new CreateNewAirlinerJPanel(userControlDisplayPanel,aCatalog);
        userControlDisplayPanel.add("CreateAirline",panel);
        CardLayout layout =(CardLayout)userControlDisplayPanel.getLayout();
        layout.next(userControlDisplayPanel);
        
    }//GEN-LAST:event_btnCreateAirlineActionPerformed

    private void btnViewAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAirlineActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblManageAirliner.getSelectedRow();
        
        if(selectedRow<0)
        {
            JOptionPane.showMessageDialog(null,"Please select a row from the data first","Warning!",JOptionPane.WARNING_MESSAGE);
          
        }
        else{
            Airliner airliner =(Airliner) tblManageAirliner.getValueAt(selectedRow,0);
            ViewAirlinerJPanel panel = new ViewAirlinerJPanel(userControlDisplayPanel,airliner);
            userControlDisplayPanel.add("ViewAirline",panel);
            CardLayout layout = (CardLayout)userControlDisplayPanel.getLayout();
            layout.next(userControlDisplayPanel);
        
        }
        
    }//GEN-LAST:event_btnViewAirlineActionPerformed

    private void btnUpdateAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAirlineActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblManageAirliner.getSelectedRow();
        
        if(selectedRow<0)
        {
            JOptionPane.showMessageDialog(null,"Please select a row from the data to be Updated","Warning!",JOptionPane.WARNING_MESSAGE);
          
        }
        else{
            Airliner airliner =(Airliner) tblManageAirliner.getValueAt(selectedRow,0);
            UpdateAirlinerJPanel panel = new UpdateAirlinerJPanel(userControlDisplayPanel,airliner);
            userControlDisplayPanel.add("UpdateAirlinerJPanel",panel);
            CardLayout layout = (CardLayout)userControlDisplayPanel.getLayout();
            layout.next(userControlDisplayPanel);
        
        }
        
        
    }//GEN-LAST:event_btnUpdateAirlineActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
                     int selectedRow = tblManageAirliner.getSelectedRow();
        
        if(selectedRow >= 0)
        {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null,"Would you like to delete the account details?","Warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION)
            {
             
            Airliner air1 =(Airliner)tblManageAirliner.getValueAt(selectedRow, 0);
             //Airliner airline = aCatalog.addAirliner();   
             aCatalog.cancelAirliner(air1);
               
             
             
             populateTable();
            
            }
           
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please select row from table first","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreateAirline;
    private javax.swing.JButton btnUpdateAirline;
    private javax.swing.JButton btnViewAirline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManageAirliner;
    // End of variables declaration//GEN-END:variables

    private void populateDets() {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
     DefaultTableModel dtm = (DefaultTableModel)tblManageAirliner.getModel();
        dtm.setRowCount(0);
        
        
        for(Airliner ai:aCatalog.getAirliner())
        {
            Object[] row = new Object[2];
            row[0]=ai;
            row[1]=ai.getAirlinerName();
            
            dtm.addRow(row);
        
        
        }
    
    
    
    
    }
}
