/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ManageAirliners;

import Business.Airliner;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Siddhi
 */
public class ViewAirlinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAirlinerJPanel
     */
    
    private JPanel userControlDisplayPanel;
    private Airliner airliner;
    
    public ViewAirlinerJPanel(JPanel userControlDisplayPanel,Airliner airliner) {
        initComponents();
        this.airliner = airliner;
        this.userControlDisplayPanel = userControlDisplayPanel;
        
        populateViewAirlineDetails();
        txtAirlineName.setText(airliner.getAirlinerName());
        txtAirlineID.setText(airliner.getAirlineID());
        txtAirlineComapny.setText(airliner.getAirlineCompany());
        txtAirlineFleetSize.setText(String.valueOf(airliner.getFleetSize()));
        txtAirlineHeadQuarters.setText(airliner.getHeadquarters());
        
    }
    
    public void populateViewAirlineDetails()
    {
        txtAirlineID.setText(airliner.getAirlineID());
        txtAirlineName.setText(airliner.getAirlinerName());
        txtAirlineComapny.setText(airliner.getAirlineCompany());
        txtAirlineFleetSize.setText(String.valueOf(airliner.getFleetSize()));
        txtAirlineHeadQuarters.setText(airliner.getHeadquarters());
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAirlineID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAirlineName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAirlineComapny = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAirlineFleetSize = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAirlineHeadQuarters = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("VIEW AIRLINER DETAILS");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Airline ID :");

        txtAirlineID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAirlineID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirlineIDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Airline Name :");

        txtAirlineName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAirlineName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirlineNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Airline Company :");

        txtAirlineComapny.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAirlineComapny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirlineComapnyActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Fleet Size : ");

        txtAirlineFleetSize.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAirlineFleetSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirlineFleetSizeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Head Quarters :");

        txtAirlineHeadQuarters.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAirlineHeadQuarters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirlineHeadQuartersActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("< Back");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jLabel6)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAirlineFleetSize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txtAirlineComapny, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAirlineName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAirlineID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAirlineHeadQuarters)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnBack)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAirlineID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAirlineName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAirlineComapny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAirlineFleetSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAirlineHeadQuarters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(218, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAirlineIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirlineIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirlineIDActionPerformed

    private void txtAirlineNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirlineNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirlineNameActionPerformed

    private void txtAirlineComapnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirlineComapnyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirlineComapnyActionPerformed

    private void txtAirlineFleetSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirlineFleetSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirlineFleetSizeActionPerformed

    private void txtAirlineHeadQuartersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirlineHeadQuartersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirlineHeadQuartersActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userControlDisplayPanel.remove(this);
        CardLayout layout=(CardLayout)userControlDisplayPanel.getLayout();
        layout.previous(userControlDisplayPanel);
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAirlineComapny;
    private javax.swing.JTextField txtAirlineFleetSize;
    private javax.swing.JTextField txtAirlineHeadQuarters;
    private javax.swing.JTextField txtAirlineID;
    private javax.swing.JTextField txtAirlineName;
    // End of variables declaration//GEN-END:variables
}
