/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import business.CarInformationList;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Siddhi
 */
public class CarMngeWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcesscontainer;
    private CarInformationList carInformationList;
    /**
     * Creates new form CarMngeWorkAreaJPanel
     */
     CarMngeWorkAreaJPanel(JPanel userProcesscontainer, CarInformationList carInformationList) {
        initComponents();
        this.userProcesscontainer = userProcesscontainer;
        this.carInformationList = carInformationList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageCarInfo = new javax.swing.JButton();
        btnCreateCarInfo = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(255, 255, 204));

        btnManageCarInfo.setBackground(new java.awt.Color(204, 204, 204));
        btnManageCarInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnManageCarInfo.setText("Manage Car Details");
        btnManageCarInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageCarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCarInfoActionPerformed(evt);
            }
        });

        btnCreateCarInfo.setBackground(new java.awt.Color(204, 204, 204));
        btnCreateCarInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCreateCarInfo.setText("Create Car Details");
        btnCreateCarInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreateCarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCarInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btnManageCarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(712, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(89, 89, 89)
                    .addComponent(btnCreateCarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(710, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(btnManageCarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(620, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(btnCreateCarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(711, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateCarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCarInfoActionPerformed
        // TODO add your handling code here:
        CreateCarJPanel panel = new CreateCarJPanel(userProcesscontainer,carInformationList);
        userProcesscontainer.add("CarMngeWorkAreaJPanel",panel);
        CardLayout layout = (CardLayout) userProcesscontainer.getLayout();
        layout.next(userProcesscontainer);
        
        
    }//GEN-LAST:event_btnCreateCarInfoActionPerformed

    private void btnManageCarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCarInfoActionPerformed
        // TODO add your handling code here:
        ManageCarDetailsJPanel panel = new ManageCarDetailsJPanel(userProcesscontainer,carInformationList);
        userProcesscontainer.add("CarMngeWorkAreaJPanel",panel);
        CardLayout layout = (CardLayout) userProcesscontainer.getLayout();
        layout.next(userProcesscontainer);
    }//GEN-LAST:event_btnManageCarInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCarInfo;
    private javax.swing.JButton btnManageCarInfo;
    // End of variables declaration//GEN-END:variables
}
