/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import business.Car;
import business.CarInformationList;
import java.awt.CardLayout;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Siddhi
 */
public class ManageCarDetailsJPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form ManageCarDetailsJPanel
     */
     private JPanel userProcesscontainer;
     private CarInformationList carInformationList;
     
     public ManageCarDetailsJPanel(JPanel userProcesscontainer,CarInformationList carInformationList) {
        initComponents();
        this.userProcesscontainer = userProcesscontainer;
        this.carInformationList = carInformationList;
        populateTable();
    }
     
     private void populateTable()
     {
         DefaultTableModel dtm = (DefaultTableModel) tblCarDetails.getModel();
         dtm.setRowCount(0);
         
         for(Car car:carInformationList.getCarList())
         {
             Object[] row = new Object[10]; 
             row[0]=car;
             //row[1]=car.getBrand();
             row[1]=car.getManufactured_year();
             row[2]=car.getMin_seats();
             row[3]=car.getMax_seats();
             row[4]=car.getSerial_num();
             row[5]=car.getModel_num();
             row[6]=car.getAvailble_city();
             row[7]=car.isMaintenance_certificate();
             row[8]=car.isAvailable();
             
             dtm.addRow(row);
         }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarDetails = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtCity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBrandName = new javax.swing.JTextField();
        txtManufYear = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMaximumSeats = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMinimumSeats = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        btnSearchBrandName = new javax.swing.JButton();
        btnSearchByManuYear = new javax.swing.JButton();
        btnSerialNumber = new javax.swing.JButton();
        btnSearchModelNo = new javax.swing.JButton();
        txtModelNo = new javax.swing.JTextField();
        btnSortbySeats = new javax.swing.JButton();
        btnCarManu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtManuSearch = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 204));

        tblCarDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand Name", "Manufactured Year", "Minimum Seats", "Maximum Seats", "Serial Number", "Model Number", "Available City", "Maintenance Certificate", "Availability"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarDetails);
        if (tblCarDetails.getColumnModel().getColumnCount() > 0) {
            tblCarDetails.getColumnModel().getColumn(0).setResizable(false);
            tblCarDetails.getColumnModel().getColumn(1).setResizable(false);
            tblCarDetails.getColumnModel().getColumn(2).setResizable(false);
            tblCarDetails.getColumnModel().getColumn(3).setResizable(false);
            tblCarDetails.getColumnModel().getColumn(4).setResizable(false);
            tblCarDetails.getColumnModel().getColumn(5).setResizable(false);
            tblCarDetails.getColumnModel().getColumn(6).setResizable(false);
            tblCarDetails.getColumnModel().getColumn(7).setResizable(false);
            tblCarDetails.getColumnModel().getColumn(8).setResizable(false);
        }

        btnSearch.setBackground(new java.awt.Color(204, 204, 204));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setText("Search By City");
        btnSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnViewDetails.setBackground(new java.awt.Color(204, 204, 204));
        btnViewDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewDetails.setText("View");
        btnViewDetails.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("<Back");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Car Details");

        txtBrandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Maximum Seats:");

        txtMaximumSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaximumSeatsActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Minimum Seats:");

        txtMinimumSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinimumSeatsActionPerformed(evt);
            }
        });

        txtSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNumberActionPerformed(evt);
            }
        });

        btnSearchBrandName.setBackground(new java.awt.Color(204, 204, 204));
        btnSearchBrandName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchBrandName.setText("Search By Brand Name");
        btnSearchBrandName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearchBrandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBrandNameActionPerformed(evt);
            }
        });

        btnSearchByManuYear.setBackground(new java.awt.Color(204, 204, 204));
        btnSearchByManuYear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchByManuYear.setText("Search By Manufactured Year");
        btnSearchByManuYear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearchByManuYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByManuYearActionPerformed(evt);
            }
        });

        btnSerialNumber.setBackground(new java.awt.Color(204, 204, 204));
        btnSerialNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSerialNumber.setText("Search By Serial Number");
        btnSerialNumber.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerialNumberActionPerformed(evt);
            }
        });

        btnSearchModelNo.setBackground(new java.awt.Color(204, 204, 204));
        btnSearchModelNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearchModelNo.setText("Search By Model Number");
        btnSearchModelNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSearchModelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchModelNoActionPerformed(evt);
            }
        });

        txtModelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNoActionPerformed(evt);
            }
        });

        btnSortbySeats.setBackground(new java.awt.Color(204, 204, 204));
        btnSortbySeats.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSortbySeats.setText("Sort By seats");
        btnSortbySeats.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSortbySeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortbySeatsActionPerformed(evt);
            }
        });

        btnCarManu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCarManu.setText("List Car Manufacturers ");
        btnCarManu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCarManu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarManuActionPerformed(evt);
            }
        });

        txtManuSearch.setColumns(20);
        txtManuSearch.setRows(5);
        jScrollPane2.setViewportView(txtManuSearch);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCarManu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearchByManuYear, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearchBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearchModelNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtManufYear, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtBrandName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtModelNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtMinimumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtMaximumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnSortbySeats, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 121, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchBrandName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMinimumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtMaximumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManufYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchByManuYear)
                    .addComponent(btnSortbySeats))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerialNumber)
                    .addComponent(btnSerialNumber))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchModelNo)
                    .addComponent(txtModelNo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnCarManu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDetails)
                    .addComponent(btnDelete))
                .addGap(119, 119, 119))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcesscontainer.remove(this);
        CardLayout layout = (CardLayout) userProcesscontainer.getLayout();
        layout.previous(userProcesscontainer);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCarDetails.getSelectedRow();
        
        if(selectedRow >= 0)
        {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null,"Would you like to delete the account details?","Warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION)
            {
             
             Car car =(Car)tblCarDetails.getValueAt(selectedRow, 0);
                carInformationList.deleteCar(car);
                populateTable();
            
            }
           
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please select row from table first","Warning",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblCarDetails.getSelectedRow();
         if(selectedRow<0)
         {
              JOptionPane.showMessageDialog(null,"Please select row from table first to view details","Warning",JOptionPane.WARNING_MESSAGE);
         }
         else
         {
             Car car =(Car) tblCarDetails.getValueAt(selectedRow,0);
             ViewCarJPanel panel = new ViewCarJPanel(userProcesscontainer,car);
             userProcesscontainer.add("ViewCarJPanel",panel);
             CardLayout layout = (CardLayout) userProcesscontainer.getLayout();
             layout.next(userProcesscontainer);
         }
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        //Search by City Name
       //Car result = carInformationList.searchCar(txtCity.getText());
       
       String city = txtCity.getText();
       
        //Validations
        if(city == null || city.equals(""))
        {
        JOptionPane.showMessageDialog(null,"Please enter the city name","Information",JOptionPane.INFORMATION_MESSAGE);
        return;
        
        }
        else{
        
        SearchCityJPanel panel = new SearchCityJPanel(userProcesscontainer, carInformationList, city);
        userProcesscontainer.add("SearchCityJPanel",panel);
        CardLayout layout = (CardLayout) userProcesscontainer.getLayout();
        layout.next(userProcesscontainer);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtBrandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandNameActionPerformed

    private void txtMaximumSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaximumSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaximumSeatsActionPerformed

    private void txtMinimumSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinimumSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinimumSeatsActionPerformed

    private void txtSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumberActionPerformed

    private void btnSearchBrandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBrandNameActionPerformed
        // TODO add your handling code here:
        //Search by City Name
        //Car result = carInformationList.searchCar(txtCity.getText());
        String branName = txtBrandName.getText();
        
      if(branName == null || branName.equals(""))
      {
       JOptionPane.showMessageDialog(null,"Brand name you entered does not exist","Information",JOptionPane.INFORMATION_MESSAGE);
       return;
      }else{
        SearchByJPanel panel = new SearchByJPanel(userProcesscontainer, carInformationList, branName);
        userProcesscontainer.add("SearchByJPanel",panel);
        CardLayout layout = (CardLayout) userProcesscontainer.getLayout();
        layout.next(userProcesscontainer);
      }
    }//GEN-LAST:event_btnSearchBrandNameActionPerformed

    private void btnSearchByManuYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByManuYearActionPerformed
        // TODO add your handling code here:
        
        int searchBy;
       
        try{
            
            searchBy = Integer.parseInt(txtManufYear.getText());
            FilterByJPanel panel = new FilterByJPanel(userProcesscontainer, carInformationList, searchBy);
            userProcesscontainer.add("FilterByJPanel",panel);
            CardLayout layout = (CardLayout) userProcesscontainer.getLayout();
            layout.next(userProcesscontainer);
            
        }
        catch(NumberFormatException e)
        {
        JOptionPane.showMessageDialog(null,"Please enter manufactured year!!","Information",JOptionPane.INFORMATION_MESSAGE);
        return;
        }
        
        
        
        /*if(txtManufYear.getText() == null || txtManufYear.getText().equals(""))
        {JOptionPane.showMessageDialog(null,"Manufactured Year you entered does not exist","Information",JOptionPane.INFORMATION_MESSAGE);
        return;
        }
        else{
        FilterByJPanel panel = new FilterByJPanel(userProcesscontainer, carInformationList, searchBy);
        userProcesscontainer.add("FilterByJPanel",panel);
        CardLayout layout = (CardLayout) userProcesscontainer.getLayout();
        layout.next(userProcesscontainer);
        }
        }catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null,"Please enter Manufactured Year!!");
        }
        */
    }//GEN-LAST:event_btnSearchByManuYearActionPerformed

    private void btnSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerialNumberActionPerformed
        // TODO add your handling code here:
        int searchBy;
        
        try{
            searchBy=Integer.parseInt(txtSerialNumber.getText());
        
        }catch(NumberFormatException e)
        {
        
        JOptionPane.showMessageDialog(null,"Please enter Serial number","Information",JOptionPane.INFORMATION_MESSAGE);
        return;
        
        
        }
        
        FilterByJPanel panel = new FilterByJPanel(userProcesscontainer, carInformationList,searchBy);
        userProcesscontainer.add("FilterByJPanel",panel);
        CardLayout layout = (CardLayout) userProcesscontainer.getLayout();
        layout.next(userProcesscontainer);
        
        /*
        int searchBy = Integer.parseInt(txtSerialNumber.getText());
        if(txtSerialNumber.getText() == null || txtSerialNumber.getText().equals(""))
        {
        JOptionPane.showMessageDialog(null,"Serial Number you entered does not exist","Information",JOptionPane.INFORMATION_MESSAGE);
        return;
        }
        else
        { FilterByJPanel panel = new FilterByJPanel(userProcesscontainer, carInformationList,searchBy);
        userProcesscontainer.add("FilterByJPanel",panel);
        CardLayout layout = (CardLayout) userProcesscontainer.getLayout();
        layout.next(userProcesscontainer);
        }*/
        
    }//GEN-LAST:event_btnSerialNumberActionPerformed

    private void btnSearchModelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchModelNoActionPerformed
        // TODO add your handling code here:
        String branName = txtModelNo.getText();
        
        
        
        if(branName == null || branName.equals("") )
        {
        JOptionPane.showMessageDialog(null,"Model Number you entered does not exist","Information",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
        SearchByJPanel panel = new SearchByJPanel(userProcesscontainer, carInformationList, branName);
        userProcesscontainer.add("SearchByJPanel",panel);
        CardLayout layout = (CardLayout) userProcesscontainer.getLayout();
        layout.next(userProcesscontainer);
        }
    }//GEN-LAST:event_btnSearchModelNoActionPerformed

    private void txtModelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNoActionPerformed

    private void btnSortbySeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortbySeatsActionPerformed
        // TODO add your handling code here:
       
        int minSeats = Integer.parseInt(txtMinimumSeats.getText());
        int maxSeats = Integer.parseInt(txtMaximumSeats.getText());
       
        if(txtMinimumSeats.getText() == null && txtMinimumSeats.getText().equals("") && txtMaximumSeats.getText() == null && txtMaximumSeats.getText().equals("") )
        {
        JOptionPane.showMessageDialog(null,"Minimum Number or Maximum Number you entered does not exist","Information",JOptionPane.INFORMATION_MESSAGE);
        return;
        
        }else{
         MinMaxSeatsJPanel panel = new MinMaxSeatsJPanel(userProcesscontainer, carInformationList, minSeats, maxSeats);
        userProcesscontainer.add("MinMaxSeatsJPanel",panel);
        CardLayout layout = (CardLayout) userProcesscontainer.getLayout();
        layout.next(userProcesscontainer);
}
        
    }//GEN-LAST:event_btnSortbySeatsActionPerformed

    private void btnCarManuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarManuActionPerformed
        // TODO add your handling code here:
       Set<String> set = new HashSet<String>();
       
       for(Car ab: CarInformationList.carList)
       {
       set.add(ab.getBrand());
       
       }
       StringBuilder sb = new StringBuilder();
       
       for(String i : set)
       {
           sb.append(i==null ?" ":i.toString());
           sb.append("\n");
       
       }
       txtManuSearch.setText(String.valueOf(sb));
        
        
        /*
        ListCarManufacturers panel = new ListCarManufacturers(userProcesscontainer, carInformationList);
        userProcesscontainer.add("ListCarManufacturers",panel);
        CardLayout layout = (CardLayout) userProcesscontainer.getLayout();
        layout.next(userProcesscontainer);
        */
        
        
    }//GEN-LAST:event_btnCarManuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarManu;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchBrandName;
    private javax.swing.JButton btnSearchByManuYear;
    private javax.swing.JButton btnSearchModelNo;
    private javax.swing.JButton btnSerialNumber;
    private javax.swing.JButton btnSortbySeats;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCarDetails;
    private javax.swing.JTextField txtBrandName;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextArea txtManuSearch;
    private javax.swing.JTextField txtManufYear;
    private javax.swing.JTextField txtMaximumSeats;
    private javax.swing.JTextField txtMinimumSeats;
    private javax.swing.JTextField txtModelNo;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
