/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.TravelAgency;

import userInterface.TravelAgency.SearchFlights;
import Business.Airplane;
import Business.AirplaneCatalog;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Siddhi
 */
public class FlightDetails extends javax.swing.JPanel {
    private JPanel userControlDisplayPanel;
    private AirplaneCatalog aCatalog;
    private Airplane airplane;

    /**
     * Creates new form FlightDetails
     */
    public FlightDetails(JPanel userControlDisplayPanel, Airplane airplane) {
        initComponents();
        this.airplane = airplane;
        this.userControlDisplayPanel = userControlDisplayPanel;
        populateDetails();
    }

    public void populateDetails(){
        TextFieldAirlinerName.setText(airplane.getAirlinerName());
        TextFieldAirlinerID.setText(airplane.getAirlineID());
        TextFieldFlightNumber.setText(String.valueOf(airplane.getFlightNumber()));
        TextFieldManName.setText(airplane.getManufacturerName());
        TextFieldSource.setText(airplane.getFromLocation());
        TextFieldDestination.setText(airplane.getToLocation());
        TextFieldModelNumber.setText(airplane.getModelNumber());
        TextFieldArrivalTime.setText(airplane.getArrival());
        TextFieldDepartureTime.setText(airplane.getDeparture());
   }
      
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblAirlinerID = new javax.swing.JLabel();
        TextFieldAirlinerName = new javax.swing.JTextField();
        lblAirlinerName = new javax.swing.JLabel();
        lblFlightNumber = new javax.swing.JLabel();
        lblModelNumber = new javax.swing.JLabel();
        lblManName = new javax.swing.JLabel();
        lblSource = new javax.swing.JLabel();
        lblDestination = new javax.swing.JLabel();
        lblDepartureTime = new javax.swing.JLabel();
        lblArrivalTime = new javax.swing.JLabel();
        TextFieldManName = new javax.swing.JTextField();
        TextFieldAirlinerID = new javax.swing.JTextField();
        TextFieldFlightNumber = new javax.swing.JTextField();
        TextFieldModelNumber = new javax.swing.JTextField();
        TextFieldSource = new javax.swing.JTextField();
        TextFieldDestination = new javax.swing.JTextField();
        TextFieldArrivalTime = new javax.swing.JTextField();
        TextFieldDepartureTime = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FLIGHT DETAILS");

        lblAirlinerID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAirlinerID.setText("Airliner ID:");

        lblAirlinerName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAirlinerName.setText("Airliner Name:");

        lblFlightNumber.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblFlightNumber.setText("Flight Number:");

        lblModelNumber.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblModelNumber.setText("Model Number:");

        lblManName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblManName.setText("Manufacturer Name:");

        lblSource.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSource.setText("Source:");

        lblDestination.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDestination.setText("Destination:");

        lblDepartureTime.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDepartureTime.setText("Departure Time:");

        lblArrivalTime.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblArrivalTime.setText("Arrival Time:");

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextFieldAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(93, 93, 93)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(136, 136, 136)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblAirlinerID)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextFieldAirlinerID, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblFlightNumber)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextFieldFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblModelNumber)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextFieldModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblManName)
                                        .addComponent(lblSource)
                                        .addComponent(lblDestination)
                                        .addComponent(lblArrivalTime)
                                        .addComponent(lblDepartureTime))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TextFieldDepartureTime, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TextFieldArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TextFieldDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TextFieldSource, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TextFieldManName, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(254, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addComponent(lblAirlinerName)
                    .addContainerGap(456, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addComponent(TextFieldAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAirlinerID)
                    .addComponent(TextFieldAirlinerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFlightNumber)
                    .addComponent(TextFieldFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblModelNumber)
                    .addComponent(TextFieldModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManName)
                    .addComponent(TextFieldManName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSource)
                    .addComponent(TextFieldSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDestination)
                    .addComponent(TextFieldDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArrivalTime)
                    .addComponent(TextFieldArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartureTime)
                    .addComponent(TextFieldDepartureTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addComponent(lblAirlinerName)
                    .addContainerGap(424, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        SearchFlights panel = new SearchFlights(userControlDisplayPanel, aCatalog);
        userControlDisplayPanel.add("Search Flights",panel);
        CardLayout layout = (CardLayout)userControlDisplayPanel.getLayout();
        layout.next(userControlDisplayPanel);

    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldAirlinerID;
    private javax.swing.JTextField TextFieldAirlinerName;
    private javax.swing.JTextField TextFieldArrivalTime;
    private javax.swing.JTextField TextFieldDepartureTime;
    private javax.swing.JTextField TextFieldDestination;
    private javax.swing.JTextField TextFieldFlightNumber;
    private javax.swing.JTextField TextFieldManName;
    private javax.swing.JTextField TextFieldModelNumber;
    private javax.swing.JTextField TextFieldSource;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAirlinerID;
    private javax.swing.JLabel lblAirlinerName;
    private javax.swing.JLabel lblArrivalTime;
    private javax.swing.JLabel lblDepartureTime;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblFlightNumber;
    private javax.swing.JLabel lblManName;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblSource;
    // End of variables declaration//GEN-END:variables

    
}
