/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.TravelAgency;
import Business.Airliner;
import Business.AirlinerCatalog;
import Business.Airplane;
import Business.AirplaneCatalog;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Siddhi
 */
public class ListAllFlights extends javax.swing.JPanel {
private JPanel userControlDisplayPanel;
private AirplaneCatalog aCatalog;
private AirplaneCatalog airplaneC;



    /**
     * Creates new form ListAll
     */
     public ListAllFlights( JPanel userControlDisplayPanel,AirplaneCatalog aCatalog ) {
        initComponents();
        this.userControlDisplayPanel= userControlDisplayPanel;
        this.aCatalog= aCatalog;
        
        populateTable();
    }
     
     public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblSearchFlights.getModel();
        dtm.setNumRows(0);
       
        for(Airplane vs: aCatalog.getAirlinerCatalog())
        {
            Object row[] = new Object[10];
          row[0]= vs.getAirlinerName();
            //row[0]=vs;
            row[1]= vs.getAirlineID();
            row[2]= vs.getFlightNumber();
            row[3]= vs.getModelNumber();
            row[4]= vs.getManufacturerName();
            row[5]= vs.getFromLocation();
            row[6]= vs.getToLocation();
            row[9]= vs.getSeatPrice();
            row[7]= vs.getArrival();
            row[8]= vs.getDeparture();
           
             dtm.addRow(row);
             
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchFlights = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LIST ALL FLIGHTS");

        tblSearchFlights.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tblSearchFlights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline Name", "Airline ID", "Flight Number", "Model Number", "Manufacturer", "From", "To", "Arrival Time", "Departure Time", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSearchFlights);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSearchFlights;
    // End of variables declaration//GEN-END:variables
}
